### ISSUE TITLE
Fonts are not working

### ISSUE THREAD

**Issue by DrHonk71** [Sevin7/7HUD#60]
I could be stupid or im just high but for some odd reason the fonts are not working for me.
 
Note that I am using a Mac Book Air

Extra/Minor Problem: On Casual the text displaying how much exp you have and how much is needed to rank up are not really alined 
http://imgur.com/VgzVag5

If it is just my computer im fine with it but its just me having that detailed personality where everything must match the product in the picture :3

**Comment by Sevin7** [comment]
The HUD was not designed for Macs. I used to have one, but I built my PC
almost a couple years ago now and have been designing it for PC's since
then. Everything is designed on my PC at 1920x1080, so things are bound to
be misaligned especially on Macs with tiny screens. What fonts aren't
working? The Mac version uses a different font because the Windows font is
not compatible with Macs.

**Comment by DrHonk71** [comment]
both the Health and Ammo fonts are not working

**Comment by Sevin7** [comment]
Yeah, those use Dock11. Look that up on dafont, they should look like that.

Get Outlook for iOS




On Wed, Aug 3, 2016 at 10:24 PM -0400, "DrHonk71" <notifications@github.com> wrote:












both the Health and Ammo fonts are not working

**Comment by DrHonk71** [comment]
Alrighty thanks
