### ISSUE TITLE
Display Rank on Scoreboard

### ISSUE THREAD

**Issue by piluke** [Sevin7/7HUD#64]
Hi, great hud btw :)

Is it possible to display each player's rank on the scoreboard for casual and comp matches?

**Comment by Sevin7** [comment]
Yes, it is. I removed the feature several months ago because it looked ugly. You can add it back by changing the "medals_width" in scoreboard.res to 5.

Get Outlook for iOS




On Mon, Nov 7, 2016 at 9:05 AM -0500, "Luke" <notifications@github.com> wrote:












Hi, great hud btw :)


Is it possible to display each player's rank on the scoreboard for casual and comp matches?

**Comment by piluke** [comment]
Okay, thanks!
